<script>
    function add(xp, yp){
        return Promise.all([xp, yp])
        .then(function(values){
            return values[0] + values[1];
        });
    }

    // add(fetchX(), fetchY())
    // .then(function(sum){
    //     console.log(sum);
    // }, function(err){
    //     console.log(err);
    // });


    // var t = {then:function(){}};

    // var obj = Object.create(t);
    // if('then' in obj){
    //     console.log("then exists in obj");
    // }

    // Object.prototype.then = function(){};

    // var strObj = {};
    // var arrObj = [];
    // if('then' in strObj){
    //     console.log("then exists in strObj");
    // }
    // if('then' in arrObj){
    //     console.log("then exists in arrObj");
    // }

    // then exists in obj
    // then exists in strObj
    // then exists in arrObj

    function immediaPromise(){
        return new Promise(function(resolve){
            resolve('hello immedia promise.');
        });
    }

    // immediaPromise().then(function(data){
    //     console.log(data);
    // });

    // hello immedia promise.

    // var ip = immediaPromise();
    // ip.then(function(){
    //     console.log(1);
    //     ip.then(function(){
    //         console.log(3);
    //     });
    // });

    // ip.then(function(){
    //     console.log(2);
    // });

    // 1
    // 2
    // 3

    function multiPromise(){       

        let p1 = new Promise(function(resolve){
            console.log('enter p1 promise');
            resolve(new Promise(function(resolve){
                console.log('enter p1 inner promise');
                resolve(1);
            }));
        });

        p1.then(function(){
            console.log('p1 finish');
        })

        let p2 = new Promise(function(resolve){
            console.log('enter p2 promise');
            // resolve(new Promise(function(resolve){
            //     console.log('enter p2 inner promise');
            //     resolve(2)
            // }));
            resolve(2);  
            
        });

        

        p2.then(function(){
            console.log('p2 finish');
        });
    }

    // multiPromise();

    // enter p1 promise
    // enter p1 inner promise
    // enter p2 promise
    // p2 finish
    // p1 finish

function cancelPromise(delay){
    return new Promise(function(resolve, reject){
        setTimeout(() => {
            reject('promise is timeout.');
        }, delay);
    });
}  

function longTimeTask(){
    return new Promise(function(resolve){
        setTimeout(() => {           
            resolve(1);
        }, 4000);
    });
}

// Promise.race([longTimeTask(), cancelPromise(2000)]).then(function(data){
//     console.log('long time task finished.');
// },function(err){
//     console.log('long time task is cancled.');
// });
 
// long time task is cancled.




function promiseStatus() {
    let p1 = Promise.resolve(1);
    console.log(p1);
    p2 = p1.then(function (data) {
        console.log(data);
        return data * 2;
    });
    console.log(p2);

    let p3 = p2.then(function (data) {
        console.log(data);
        console.log(p2);
    });
}

// promiseStatus();

// Promise {<fulfilled>: 1}
// 	__proto__: Promise
// 	[[PromiseState]]: "fulfilled"
// 	[[PromiseResult]]: 1
	
// PromiseÂ {<pending>}
// 	__proto__: Promise
// 	[[PromiseState]]: "pending"
// 	[[PromiseResult]]: undefined
	
// 1
// 2

// Promise {<fulfilled>: 2}
// 	__proto__: Promise
// 	[[PromiseState]]: "fulfilled"
// 	[[PromiseResult]]: 2


function exceprionPromise(){
    let p = new Promise(function(resolve){
        exceptionFuncInPromise();
        resolve(1);
    });

    var p1 = p.then(function(data){
            console.log('promise execute sucessful');
        },function(err){
            console.log('promise execute error, exception is ' + err);
            exceptionFuncInThen();
    });

    p1.then(function(data){
        console.log('then execute sucessful');
    }, function(err){
        console.log('then execute error, exception is ' + err);
    });
}

// exceprionPromise();

// promise execute error, exception is ReferenceError: exceptionFuncInPromise is not defined
// promise.html:185 then execute error, exception is ReferenceError: exceptionFuncInThen is not defined
</script>